export { participatesInLifecycleTag, ActorComponent, ActorSystem, type IActor } from "./actor"
export { type Component } from "./component"
export { entityDoesNotExistError, EntityDoesNotExistError, type EntityID } from "./entity"
export { createPrefab, type Prefab } from "./prefab"
export { circularRelationshipError, CircularRelationshipError, Relationship } from "./relationship"
export { System } from "./system"
export { type Tag, TagSet, tagsOf } from "./tags"
export { World } from "./world"
